---

- name: Setup Python project.
  hosts: 127.0.0.1
  connection: local
  vars:
    project_type: python
    project_path: .
    project_features:
      - test
      - docker
      - ci_cd
    project_python_submodules: []

    docker_image_name: internetofus/logger
    docker_python_services:
      - name: logger
        main_module: memex_logging.ws.main
        required_env_variables:
          - ${EL_HOST}
          - ${EL_PORT}
        gunicorn_app: build_production_app()
      - name: worker
        required_env_variables:
          - ${EL_HOST}
          - ${EL_PORT}
        custom_start_command: "exec celery worker -A memex_logging.celery.initialize.celery"
      - name: beat
        required_env_variables:
          - ${EL_HOST}
          - ${EL_PORT}
        custom_start_command: "exec celery beat -A memex_logging.celery.initialize.celery -s /celery/celerybeat-schedule"
      - name: migrator
        required_env_variables:
          - ${EL_HOST}
          - ${EL_PORT}
        custom_start_command: "exec python -m memex_logging.migration.migration"
    docker_registry: docker.io

    ci_environments:
      mr:
        stages:
          - name: test
            type: unit
            in_docker: false
            manual: false
          - name: test
            type: coverage
            in_docker: false
            manual: false
      staging:
        stages:
          - name: build
            manual: true
          - name: build
            type: badge
            manual: true
          - name: test
            type: unit
            in_docker: false
          - name: test
            type: coverage
            in_docker: false
            manual: true
          - name: push
          - name: trigger
            manual: true
            git_ref: develop
      production:
        stages:
          - name: build
          - name: build
            type: badge
            manual: true
          - name: test
            type: unit
            in_docker: false
          - name: test
            type: coverage
            in_docker: false
            manual: true
          - name: push
          - name: notify
      default:
        stages:
          - name: test
            type: coverage
          - name: build
            type: badge
    ci_additional_badges:
      - wenet-common

  roles:
    - uh.project_template