---

- name: Setup Python project.
  hosts: 127.0.0.1
  connection: local
  vars:
    project_type: python
    project_path: .
    project_features:
      - test
      - docker
      - ci_cd
    project_python_submodules: []

    docker_image_name: internetofus/logger
    docker_python_services:
      - name: logger
        main_module: memex_logging.ws.main
        required_env_variables:
          - ${EL_HOST}
          - ${EL_PORT}
        gunicorn_app: build_production_app()
    docker_registry: docker.io

    ci_environments:
      issue:
        stages:
          - name: build
            manual: true
          - name: test
      staging:
        stages:
          - name: build
          - name: test
          - name: push
      production:
        stages:
          - name: build
          - name: test
          - name: push

  roles:
    - uh.project_template